project:
    name: Wordpad
    operations:
        - trace
        # - reduce
        # - minimize
    filter:
        mode: exclude
        # mode: include
    modules:
        - <unknown>
        - C:\DynamoRIO\lib32\release\dynamorio.dll
        - C:\DynamoRIO\tools\lib32\release\drcov.dll
        # - C:\Program Files\Windows NT\Accessories\wordpad.exe
server:
    seed_dir: ./seeds/
    working_dir: ./projects/
client:
    host: 192.168.56.1
    drio_path: C:\DynamoRIO\bin32\drrun.exe
    target_path: C:\Program Files\Windows NT\Accessories\wordpad.exe
    target_args:
    pre_cmd:
    post_cmd:
    max_attempts: 3
    wait_time: 5
    max_timeout: 45
